import Aside from "@/components/aside";
import { UsersThree, Student, Chalkboard, BookBookmark, BookOpenText, Nut, House, BellSimple, List } from "@/utils/icons";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Administrador",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const links = [
    { name: 'Menu', href: '/', icon: House },
    { name: 'Turmas', href: '/class', icon: UsersThree },
    { name: 'Alunos', href: '/students', icon: Student },
    { name: 'Mentores', href: '/mentors', icon: Chalkboard },
    { name: 'Conteúdo Educacional', href: '/educational-content', icon: BookBookmark },
    { name: 'Instruções dos Mentores', href: '/instructions-mentors', icon: BookOpenText },
    { name: 'Configurações', href: '/settings', icon: Nut },
  ];

  return (
    <main className="flex flex-1 h-screen">
        <Aside links={links} />
        <section className="flex-1 px-5 pb-5 overflow-auto">
          <header className="flex justify-between py-12">
            <h1 className="text-2xl font-bold">Conteúdo Educacional</h1>

            <div className="flex gap-5">
                <p>Administrador</p>
                <BellSimple />
                <List />
            </div>
          </header>
          {children}
        </section>
    </main>
  );
}
