import Aside from "@/components/aside";
import Breadcrumbs from "@/components/Breadcrumbs";
import { UsersThree, Student, Chalkboard, BookBookmark, BookOpenText, Nut, House, BellSimple, List } from "@/utils/icons";
import { dashboardAside } from "@/utils/links";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Administrador",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex flex-1 h-screen">
        <Aside links={dashboardAside} />
        <section className="flex-1 px-5 pb-5 overflow-auto">
          <header className="flex items-center justify-between py-12">
            <Breadcrumbs />

            <div className="flex items-center gap-5">
                <p>Administrador</p>
                <BellSimple />
                <List />
            </div>
          </header>
          {children}
        </section>
    </main>
  );
}
